spring.application.name=smallbox

#Perfil activo
spring.profiles.active=${SPRING_PROFILE_ACTIVE:dev}

# Configuración del servidor
server.port=${PORT:8080}
#server.servlet.context-path=/api

# JWT configuración
jwt.secret=${JWT_SECRET:12345678901234567890123456789012}
jwt.expiration-time-ms=${JWT_EXPIRATION_TIME:900000}
jwt.expiration-time-refresh-ms=${JWT_EXPIRATION_TIME_REFRESH:604800000}

# Tracking number
tracking.prefix=${TRACKING_PREFIX:SB}

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=false