spring.application.name=smallbox

#Perfil activo
spring.profiles.active=${SPRING_PROFILE_ACTIVE:dev}

# Configuración del servidor
server.port=${PORT:8080}
#server.servlet.context-path=/api

# Logs
# Formato personalizado para los Logs de Consola aplicando MDC
logging.level.com.example.smallbox=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [%X{correlationId}] [%X{userId}] --- [%t] %-40.40logger{39} : %m%n
logging.output.ansi.enabled=ALWAYS

# JWT configuración
jwt.secret=${JWT_SECRET:12345678901234567890123456789012}
jwt.expiration-time-ms=${JWT_EXPIRATION_TIME:900000}
jwt.expiration-time-refresh-ms=${JWT_EXPIRATION_TIME_REFRESH:604800000}

# Tracking number
tracking.prefix=${TRACKING_PREFIX:SB}

# Docs
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=false

# Scalar
scalar.enabled=true
scalar.url=/v3/api-docs

# Scalar UI
scalar.theme=deep_space
scalar.dark-mode=true
scalar.hide-dark-mode-toggle=false
scalar.layout=modern
scalar.show-sidebar=true
